version: "3.7"

services:
    app:
        image: node:12-alpine
        command: sh -c 'npm install && npm run start'
        ports:
            - ${APP_PORT}:${APP_PORT}
        working_dir: /app
        volumes:
            - ./:/app
        env_file:
            - .env
    postgres:
        image: postgres
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - qas-postgres-data:/var/lib/postgresql/data
        env_file:
            - .env

volumes:
    qas-postgres-data: